name: create a mirror of website and zip the saved contents

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  mirror-website:
    name: mirrors the website
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: wget
      uses: wei/wget@v1
      with:
        args: -O logfile.txt -P ./actions/ https://gabriels-fantabulous-site-23ac8b.webflow.io

  zip-files:
    name: Zips the Saved file
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Prepares a zip file
      uses: montudor/action-zip@v1.0.0
      with:
        args: zip -qq -r adappt_co_uk.zip . -i /actions/gabriels-fantabulous-site-23ac8b.webflow.io
