

name: Job Execution 
on:
  workflow_dispatch:
  push:
    branches:
      - main
  issues:
    types:
      - opened 
      - reopened
  release:
    types:
      - published
      
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Download Website
      run: |
        wget --mirror --convert-links --adjust-extension --page-requisites --no-parent -P /tmp/code https://safelite.webflow.io/
    
    - name: Copy New Code
      run: |
        cp -r /tmp/code/safelite.webflow.io/* ./python/    
      continue-on-error: true
       
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
       python-version: '3.x'

    - name: Install dependencies
      run: |
       python -m pip install --upgrade pip
       pip install requests beautifulsoup4 lxml Pillow

    - name: Run script
      run: |         
          cd python
          python images.py      
      continue-on-error: true
      
       #----------------------------------------------------
    - name: Install PyGithub
      run: |            
         pip install PyGithub
         pip install requests
        
    - name: Save githublogs
      run: |            
           python '/home/runner/work/webflow2/webflow2/.github/workflows/save_github_logs.py'
          
      #----------------------------------------------------
      
    - name: Install dependencies
      run: |            
           npm install prettier --save-dev

    - name: Beautify HTML
      run: npx prettier --write "**/*.html"
    - name: Replace CSS and JS URLs in HTML files      
      run: |          
          find . -name '*.html' -exec sed -i 's|https://assets.website-files.com/6271d7fa721c60a64d063ed1/css|/css|g' {} +
          find . -name '*.html' -exec sed -i 's|https://assets.website-files.com/6271d7fa721c60a64d063ed1/js|/js|g' {} +          
    - name: Replace image URLs in HTML files  
      run: |
          find . -name '*.html' -exec sed -i 's|https://assets.website-files.com/6271d7fa721c60a64d063ed1|/images|g' {} +  
    - name: Replace Image Srcset
      run: |
        python3 - <<EOF
        from bs4 import BeautifulSoup
        import glob

        html_files = glob.glob("**/*.html", recursive=True)

        for file_path in html_files:
            with open(file_path, "r") as file:
                soup = BeautifulSoup(file, "html.parser")
                imgs = soup.find_all("img", srcset=True)
                [img.attrs.pop("srcset") for img in imgs]

            with open(file_path, "w") as file:
                file.write(soup.prettify())
        EOF
     #----------------------------------------------------
  #  - name: Install PyGithub
   #   run: |            
     #  pip install PyGithub
        
   # - name: Save githublogs
   #   run: |            
   #      python '/home/runner/work/webflow2/webflow2/.github/workflows/save_github_logs.py'
          
      #----------------------------------------------------
    - name: Read emails from JSON file
      id: read_emails
      uses: actions/github-script@v4
      with:
        script: |
          const fs = require('fs');
          const recipients = JSON.parse(fs.readFileSync('python/recipients.json'));
          const emails = recipients.recipients.map(recipient => recipient.email).join(',');
          console.log(emails);            
          core.setOutput('emails', emails);
          
    - name: Check for file changes
      id: file-changes
      run: |
         CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
         # echo "::set-output name=files::$CHANGED_FILES"    
         
    - name: Commit Code Email
      if: steps.file-changes.outputs.files != ''
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp-mail.outlook.com
        port: 587
        username: gabe.ungureanu@outlook.com
        password: askGabe4e!
        subject: "PushEvent Triggered: ${{ github.repository }}"          
        body: PushEvent Triggered! A recent push to Safelite's GitHub repository from Webflow has been successfully completed.        
        to:  ${{ steps.read_emails.outputs.emails }}
        from: gabe.ungureanu@outlook.com
        
    - name: Determine Event Type
      id: determine-event
      run: echo "::set-output name=event::${{ toJson(github.event_name) }}"
    
    - name: Send Push Email
      if: steps.determine-event.outputs.event == 'push'
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp-mail.outlook.com
        port: 587
        username: gabe.ungureanu@outlook.com
        password: askGabe4e!
        subject: "PushEvent Triggered: ${{ github.repository }}"          
        body: PushEvent Triggered! A recent push to Safelite's GitHub repository from Webflow has been successfully completed.        
        to:  ${{ steps.read_emails.outputs.emails }}
        from: gabe.ungureanu@outlook.com

    - name: Send Issues Email
      if: steps.determine-event.outputs.event == 'issues'
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp-mail.outlook.com
        port: 587
        username: gabe.ungureanu@outlook.com
        password: askGabe4e!
        subject: "IssueEvent Triggered:${{ github.repository }}"          
        body: IssueEvent Triggered! We've had some progress on the reported issues. Our team have been actively addressing them to enhance the overall user experience.
        to: ${{ steps.read_emails.outputs.emails }}
        from: gabe.ungureanu@outlook.comm

    - name: Send Release Email
      if: steps.determine-event.outputs.event == 'release'
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp-mail.outlook.com
        port: 587
        username: gabe.ungureanu@outlook.com
        password: askGabe4e!
        subject: "ReleaseEvent Triggered: ${{ github.repository }}"          
        body: ReleaseEvent Triggered! We are thrilled to announce a new release! The latest version is now available, packed with exciting features and enhancements.
        to: ${{ steps.read_emails.outputs.emails }}
        from: gabe.ungureanu@outlook.com
    
    - name: Set Git user name and email
      run: |
       git config --global user.email "gabe.ungureanu@outlook.com"
       git config --global user.name "Gabriel"
    - name: Add New Code
      run: |        
        rm -rf node_modules
        rsync -avW --delete-after --ignore-errors --exclude='.git' --exclude='.github' ./python/ ./ 
        mkdir -p python && cp -r images.py python && cp -r recipients.json python
        git status
        #git add .
        git add "/home/runner/work/webflow2/webflow2/github_logs.json"
        git commit -m "Webflow-Safelite Project"    
        git push origin main 
        sleep 20
      continue-on-error: true  
         
