name: Job Execution 
on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Download Website
      run: |
        wget --mirror --convert-links --adjust-extension --page-requisites --no-parent -P /tmp/code https://safelite.webflow.io/
    
    - name: Copy New Code
      run: |
        cp -r /tmp/code/safelite.webflow.io/* ./python/    
      continue-on-error: true
       
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
       python-version: '3.x'

    - name: Install dependencies
      run: |
       python -m pip install --upgrade pip
       pip install requests beautifulsoup4 lxml Pillow

    - name: Run script
      run: |         
          cd python
          python images.py      
      continue-on-error: true
      
    - name: Install dependencies
      run: |            
           npm install prettier --save-dev

    - name: Beautify HTML
      run: npx prettier --write "**/*.html"
    - name: Replace CSS and JS URLs in HTML files      
      run: |          
          find . -name '*.html' -exec sed -i 's|https://assets.website-files.com/6271d7fa721c60a64d063ed1/css|/css|g' {} +
          find . -name '*.html' -exec sed -i 's|https://assets.website-files.com/6271d7fa721c60a64d063ed1/js|/js|g' {} +          
    - name: Replace image URLs in HTML files  
      run: |
          find . -name '*.html' -exec sed -i 's|https://assets.website-files.com/6271d7fa721c60a64d063ed1|/images|g' {} +  
       
    - name: Remove srcset attribute      
      run: |
          find . -name "*.html" -type f -exec sed -i 's/srcset=\"[^\"]*\"/srcset=\"\"/g' {} +
    - name: Set Git user name and email
      run: |
       git config --global user.email "gabe.ungureanu@outlook.com"
       git config --global user.name "Gabriel"
    - name: Add New Code
      run: |        
        rm -rf node_modules
        rsync -avW --delete-after --ignore-errors --exclude='.git' --exclude='.github' ./python/ ./ 
        mkdir -p python && cp -r images.py python 
        git status
        git add .
        git commit -m "html beautify"    
        git push origin main 
      continue-on-error: true      
