# Simple workflow for deploying static content to GitHub Pages
name: EmailNotifications

on:
  push:
    branches:
      - main

jobs:
  send-email:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Send Email Notification
        uses: actions/email@v2
        with:
          server_address: 'smtp.office365.com'
          server_port: 587
          username: 'support@khamelia.com'
          password: 'askSign4e!'
          subject: Email Notification
          body: |
            Hello,
            
            This is a notification email sent through GitHub Actions.
            
            Regards,
            Your GitHub Workflow
          to: jai.singh@logixshapers.biz
