# Simple workflow for deploying static content to GitHub Pages
name: EmailNotifications

on:
  push:
    branches:
      - main

jobs:
  send-email:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install dependencies
        run: npm install
        
      - name: Send Email Notification
        run: node send-email.js
        env:
          SMTP_SERVER: smtp.office365.com
          SMTP_PORT: 587
          EMAIL_USERNAME: support@khamelia.com
          EMAIL_PASSWORD: askSign4e!
          EMAIL_SUBJECT: Email Notification
          EMAIL_RECIPIENT: jai.singh@logixshapers.biz
