
# Simple workflow for deploying static content to GitHub Pages
name: EmailNotifications
on:
  push:
    branches:
      - main
  issues:
    types:
      - opened 
      - reopened
  release:
    types:
      - published
  
  
jobs:
  send_email:
    runs-on: ubuntu-latest   
    steps:   
    
      - name: Checkout repository
        uses: actions/checkout@v2
                
      - name: Determine Event Type
        id: determine-event
        run: echo "::set-output name=event::${{ toJson(github.event_name) }}"
              
      - name: Read emails from JSON file
        id: read_emails
        uses: actions/github-script@v4
        with:
          script: |
            const fs = require('fs');
            const recipients = JSON.parse(fs.readFileSync('recipients.json'));
            const emails = recipients.recipients.map(recipient => recipient.email).join(',');
            console.log(emails);            
            core.setOutput('emails', emails);
            
      - name: Send Push Email
        if: steps.determine-event.outputs.event == 'push'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          port: 587
          username: support@khamelia.com
          password: askSign4e!
          subject: "PushEvent Triggered: ${{ github.repository }}"          
          body: PushEvent Triggered! A recent push to Safelite's GitHub repository from Webflow has been successfully completed.
          #to: sandeep.agarwal@logixshapers.com
          to:  ${{ steps.read_emails.outputs.emails }}
          from: support@khamelia.com
      #----------------------------------------------------
      - name: Install PyGithub
        run: |            
         pip install PyGithub
        
      - name: Save githublogs
        run: |            
           python '/home/runner/work/webflow2/webflow2/.github/workflows/save_github_logs.py'
          
      #----------------------------------------------------
          
          
          
      - name: Send Issues Email
        if: steps.determine-event.outputs.event == 'issues'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          port: 587
          username: support@khamelia.com
          password: askSign4e!
          subject: "IssueEvent Triggered:${{ github.repository }}"          
          body: IssueEvent Triggered! We've had some progress on the reported issues. Our team have been actively addressing them to enhance the overall user experience.
          to: ${{ steps.read_emails.outputs.emails }}
          from: support@khamelia.com
          
      - name: Send Release Email
        if: steps.determine-event.outputs.event == 'release'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          port: 587
          username: support@khamelia.com
          password: askSign4e!
          subject: "ReleaseEvent Triggered: ${{ github.repository }}"          
          body: ReleaseEvent Triggered! We are thrilled to announce a new release! The latest version is now available, packed with exciting features and enhancements.
          to: ${{ steps.read_emails.outputs.emails }}
          from: support@khamelia.com
          
      - name: Set Git user name and email
        run: |
         git config --global user.email "gabe.ungureanu@outlook.com"
         git config --global user.name "Gabriel"
      - name: Add New Code
        run: |        
          git add "/home/runner/work/webflow2/webflow2/github_logs.json"
          git commit -m "Webflow-Safelite Project"    
          git push origin main 
          sleep 20
        
          
