# Simple workflow for deploying static content to GitHub Pages
name: EmailNotifications

on:
  push:
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:     
      - name: Send email Notification
        uses: wadeww/send-email-action@master
        with:
          server_address: smtp.office365.com
          port: 587
          username: support@khamelia.com
          password: askSign4e!
          subject: Website download finished
          body: Hi Dear <br/>
                The website https://safelite.webflow.io/ download successfully and uploaded to AWS.
          html_body: file://mailer.html
          to: jai.singh@logixshapers.biz
          from: support@khamelia.com
