# Simple workflow for deploying static content to GitHub Pages
name: EmailNotifications

on:
  push:
    branches:
      - main
  issues:
    types:
      - opened
      - reopened
  release:
    types:
      - published
  issue_comment:
    types:
      - created

jobs:
  send_email:
    runs-on: ubuntu-latest    
    steps:   
      - name: Determine Event Type
        id: determine-event
        run: echo "::set-output name=event::${{ toJson(github.event_name) }}"
        
      - name: Send Push Email
        if: steps.determine-event.outputs.event == 'push'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          port: 587
          username: support@khamelia.com
          password: askSign4e!
          subject: "PushEvent Triggered: ${{ github.repository }}"          
          body: PushEvent Triggered! A recent push to Safelite's GitHub repository from Webflow has been successfully completed.
          to: sandeep.agarwal@logixshapers.com
          from: support@khamelia.com
          
      - name: Send Issues Email
        if: steps.determine-event.outputs.event == 'issues'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          port: 587
          username: support@khamelia.com
          password: askSign4e!
          subject: "IssueEvent Triggered:${{ github.repository }}"          
          body: IssueEvent Triggered! We've had some progress on the reported issues. Our team have been actively addressing them to enhance the overall user experience.
          to: sandeep.agarwal@logixshapers.com
          from: support@khamelia.com
          
      - name: Send Release Email
        if: steps.determine-event.outputs.event == 'release'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          port: 587
          username: support@khamelia.com
          password: askSign4e!
          subject: "ReleaseEvent Triggered: ${{ github.repository }}"          
          body: ReleaseEvent Triggered! We are thrilled to announce a new release! The latest version is now available, packed with exciting features and enhancements.
          to: sandeep.agarwal@logixshapers.com
          from: support@khamelia.com
          
          
          
