# Simple workflow for deploying static content to GitHub Pages
name: EmailNotifications

on:
  push:
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Set up sendmail
        run: sudo apt-get update && sudo apt-get install -y sendmail

      - name: Send some mail
        uses: wadeww/send-email-action@master
        with:
          server_address: smtp.office365.com
          port: 587
          username: support@khamelia.com
          password: askSign4e!
          subject: Workflow finished
          body: Job completed ${{job.status}}
          to: jai.singh@logixshapers.biz
          from: support@khamelia.com
