# Simple workflow for deploying static content to GitHub Pages
name: EmailNotifications

on:
  push:
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Set up sendmail
        run: sudo apt-get update && sudo apt-get install -y sendmail

      - name: Send email
        run: |
          echo "To: jai.singh@logixshapers.biz
          From: support@khamelia.com
          Subject: Test Email

          This is the body of the email.
          " | sendmail -t
