
# Simple workflow for deploying static content to GitHub Pages
name: EmailNotifications  
on:
  push:
    branches:
      - main
  issues:
    types:
      - opened 
      - reopened
  release:
    types:
      - published
  
jobs:
  send_email:
    runs-on: ubuntu-latest   
    steps:   
    
      - name: Checkout repository
        uses: actions/checkout@v2
                      
      - name: Determine Event Type
        id: determine-event
        run: echo "::set-output name=event::${{ toJson(github.event_name) }}"
     #-----------------------------------------------------------------------------
      - name: Update audit log        
        run: |
          # Get the current timestamp and other relevant data
          timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          repository=${GITHUB_REPOSITORY}
          pusher=${GITHUB_ACTOR}
          commit_hash=${GITHUB_SHA}
          commit_message=$(git log --format=%B -n 1 $commit_hash)
          
          # Create the JSON object for the push event
          audit_log="{\"timestamp\": \"${timestamp}\", \"repository\": \"${repository}\",\"release_manager\": \"${pusher}\", \"commit_hash\": \"${commit_hash}\", \"commit_message\": \"${commit_message}\"},"
          
          # Append the JSON object to the audit_log.json file 
          echo $audit_log >> audit_log.json
          #echo $audit_log >> audit_log_temp.json
          #mv audit_log_temp.json audit_log.json
          
          # Display the updated audit log (optional)
          cat audit_log.json
     #-----------------------------------------------------------------------------        
     
      - name: Formate audit log        
        run:  |
         python -m json.tool audit_log.json > audit_log.json
     
      - name: Read emails from JSON file
        id: read_emails
        uses: actions/github-script@v4
        with:
          script: |
            const fs = require('fs');
            const recipients = JSON.parse(fs.readFileSync('recipients.json'));
            const emails = recipients.recipients.map(recipient => recipient.email).join(',');
            console.log(emails);            
            core.setOutput('emails', emails);
            
      - name: Send Push Email
        if: steps.determine-event.outputs.event == 'push'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          port: 587
          username: support@khamelia.com
          password: askSign4e!
          subject: "PushEvent Triggered: ${{ github.repository }}"          
          body: PushEvent Triggered! A recent push to Safelite's GitHub repository from Webflow has been successfully completed.
          #to: sandeep.agarwal@logixshapers.com
          to:  ${{ steps.read_emails.outputs.emails }}
          from: support@khamelia.com
          
      #------------------------------------------------------------------------
      - name: Install PyGithub
        run: |            
         pip install PyGithub
         pip install requests        
      - name: Save githublogs
        run: |            
           python '/home/runner/work/webflow2/webflow2/.github/workflows/save_github_logs.py'
      #----------------------------------------------------
      #----------------------------------------------------
      #- name: Save auditblogs
      #  run: |            
      #     python '/home/runner/work/webflow2/webflow2/.github/workflows/save_github_auditlogs.py'      
      #----------------------------------------------------
               
      - name: Send Issues Email
        if: steps.determine-event.outputs.event == 'issues'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          port: 587
          username: support@khamelia.com
          password: askSign4e!
          subject: "IssueEvent Triggered:${{ github.repository }}"          
          body: IssueEvent Triggered! We've had some progress on the reported issues. Our team have been actively addressing them to enhance the overall user experience.
          to: ${{ steps.read_emails.outputs.emails }}
          from: support@khamelia.com
          
      - name: Send Release Email
        if: steps.determine-event.outputs.event == 'release'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          port: 587
          username: support@khamelia.com
          password: askSign4e!
          subject: "ReleaseEvent Triggered: ${{ github.repository }}"          
          body: ReleaseEvent Triggered! We are thrilled to announce a new release! The latest version is now available, packed with exciting features and enhancements.
          to: ${{ steps.read_emails.outputs.emails }}
          from: support@khamelia.com
          
      - name: Set Git user name and email
        run: |
         git config --global user.email "gabe.ungureanu@outlook.com"
         git config --global user.name "Gabriel"
      - name: Add New Code
        run: |        
          git add "/home/runner/work/webflow2/webflow2/audit_log.json"
          #git add "/home/runner/work/webflow2/webflow2/github_logs.json"
          git commit -m "Webflow-Safelite Project"    
          git push origin main 
          sleep 20
        
          
