name: Download Images
on:
  push:
    branches:
      - main # Replace with your default branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download files
        run: |
          # Create a directory for images
          mkdir -p images

      - name: Commit changes
        run: |
          git config --global user.name "Gabriel"
          git config --global user.email "gabe.ungureanu@outlook.com"
          git add images/
          git commit -m "Add images"
          git push
