name: Job Execution 
on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Download Website
      run: |
        wget --mirror --convert-links --adjust-extension --page-requisites --no-parent -P /tmp/code https://safelite.webflow.io/
    - name: Update Code in Repository
      uses: actions/checkout@v2
      with:
        ref: main # replace with the name of the branch you want to update
    #- name: Remove Old Code
     # run: |
      #  rm -rf ./*
    - name: Copy New Code
      run: |
        cp -r /tmp/code/safelite.webflow.io/* . 
    - name: Set Git user name and email
      run: |
        git config --global user.email "gabe.ungureanu@outlook.com"
        git config --global user.name "Gabriel"
    - name: Add New Code
      run: |
        git status
        git add .
        git commit -m "test2"
        git push origin main 
      continue-on-error: true
      
  imagedownload:
    needs: download
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
         python-version: '3.x'

      - name: Install dependencies
        run: |
         python -m pip install --upgrade pip
         pip install requests beautifulsoup4 lxml Pillow
      
      - name: Run script
        run: python images.py
      - name: Set Git user name and email
        run: |
          git config --global user.email "gabe.ungureanu@outlook.com"
          git config --global user.name "Gabriel"
      - name: Add New Code
        run: |
          git status
          git add .
          git pull origin main 
          git commit -m "images commit"
          git push origin main 
        continue-on-error: true
    
  replacelinks:
      needs: imagedownload
      runs-on: ubuntu-latest
      
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Replace CSS and JS URLs in HTML files      
        run: |          
            find . -name '*.html' -exec sed -i 's|https://assets.website-files.com/6271d7fa721c60a64d063ed1/css|/css|g' {} +
            find . -name '*.html' -exec sed -i 's|https://assets.website-files.com/6271d7fa721c60a64d063ed1/js|/js|g' {} +          
      - name: Replace image URLs in HTML files  
        run: |
            find . -name '*.html' -exec sed -i 's|https://assets.website-files.com/6271d7fa721c60a64d063ed1|/images|g' {} +
      - name: Set Git user name and email
        run: |
            git config --global user.email "gabe.ungureanu@outlook.com"
            git config --global user.name "Gabriel"
      - name: Add New Code
        run: |
            git status
            git add .
            git commit -m "Update link"         
            git push origin main 
        continue-on-error: true
        
  htmlbeautifier:
      needs: replacelinks
      runs-on: ubuntu-latest
    
      steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install prettier --save-dev

      - name: Beautify HTML
        run: npx prettier --write "**/*.html"
      - name: Set Git user name and email
        run: |
         git config --global user.email "gabe.ungureanu@outlook.com"
         git config --global user.name "Gabriel"
      - name: Fetch remote changes
        run: git fetch

      - name: Merge remote changes
        run: git merge origin/main

      # Additional steps as needed

      - name: Push changes
        run: git push origin main 
      continue-on-error: true
       
