name: Remove srcset attribute

on:
  push:
    branches:
      - main

jobs:
  remove_srcset:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Remove srcset attribute
      run: |
        find . -name "*.html" -type f -print0 | xargs -0 sed -i 's/srcset="[^"]*"//g'
