name: Edit Image URL

on:
  push:
    branches:
      - main

jobs:
  edit-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Edit image URL
      run: |
        sed -i 's|https://uploads-ssl.webflow.com/63ff41bea75a049e418bbd55|/images|g' index.html
    - name: Set Git user name and email
      run: |
          git config --global user.email "gabe.ungureanu@outlook.com"
          git config --global user.name "Gabriel"

    - name: Add New Code
      run: |
          git status
          git add .
          git commit -m "Update link"
          git push origin main

 
