name: Replace
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 lxml Pillow
      
    - name: Run script
      run: python replacelink.py
      
    - name: Set Git user name and email
      run: |
        git config --global user.email "gabe.ungureanu@outlook.com"
        git config --global user.name "Gabriel"
    - name: Add New Code
      run: |
        git status
        git add .
        git commit -m "test33"
        git push origin main 
