name: Audit Log

on:
  push:
    branches:
      - main # Replace 'main' with your default branch name if it's different

jobs:
  update_audit_log:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Update audit log
        run: |
          # Get the current timestamp and other relevant data
          timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          repository=${GITHUB_REPOSITORY}
          pusher=${GITHUB_ACTOR}
          commit_hash=${GITHUB_SHA}
          commit_message=$(git log --format=%B -n 1 $commit_hash)

          # Create the JSON object for the push event
          audit_log="{\"timestamp\": \"${timestamp}\", \"repository\": \"${repository}\", \"release_manager\": \"${pusher}\", \"commit_hash\": \"${commit_hash}\", \"commit_message\": \"${commit_message}\"}"

          # Use Python to format and store the audit_log object in audit_log.json
          python -c "import json; data = json.loads('''[$audit_log]'''); open('audit_log.json', 'w').write(json.dumps(data, indent=2))"

          # Display the updated audit log (optional)
          cat audit_log.json

      # Commit and push the updated audit log back to the repository
      - name: Commit and push changes
        run: |
          git config user.name "Audit Log Bot"
          git config user.email "auditlog@example.com"
          git add audit_log.json
          git commit -m "Update audit log - ${{ github.sha }}"
          git push origin main
